### ISSUE TITLE
madder root photos not appearing on sandbox

### ISSUE THREAD

**Issue by catkins2019** [cu-mkp/sandbox#107]
probably not a serious issue but I've updated the docs page and even a day later the photos haven't appeared on sandbox, should I be worried?

**Comment by njr2128** [comment]
It looks like we forgot to change the link on the https://github.com/cu-mkp/sandbox/blob/main/index.md page to the "field notes" page you're editing! We were linking it to the original assignment sheet. Fixed in my previous commit, so images and other edits should show up now! If they do, we can close this issue :)

**Comment by njr2128** [comment]
done!
